import {
  MdCheck,
  MdClose,
  MdUnfoldMore,
  MdClear,
  MdArrowForward,
  MdCardMembership,
  MdInventory,
  MdPlaylistRemove,
  MdReadMore,
  MdCheckCircleOutline,
  MdContentPasteOff,
  MdOutlineConstruction,
  MdOutlineLayers,
  MdViewColumn,
  MdShelves,
  MdAssignmentInd,
} from "react-icons/md";

export const Icons = {
  MdCheck,
  MdClose,
  MdClear,
  MdUnfoldMore,
  MdArrowForward,
  MdCardMembership,
  MdInventory,
  MdPlaylistRemove,
  MdReadMore,
  MdCheckCircleOutline,
  MdContentPasteOff,
  MdOutlineConstruction,
  MdOutlineLayers,
  MdViewColumn,
  MdShelves,
  MdAssignmentInd,
};
