import {
  MdArrowForward,
  MdAssignmentInd,
  MdCardMembership,
  MdCheck,
  MdCheckCircleOutline,
  MdClear,
  MdClose,
  MdContentPasteOff,
  MdInventory,
  MdOutlineConstruction,
  MdOutlineLayers,
  MdPlaylistRemove,
  MdReadMore,
  MdShelves,
  MdUnfoldMore,
  MdViewColumn,
} from "react-icons/md";

export const Icons = {
  MdCheck,
  MdClose,
  MdClear,
  MdUnfoldMore,
  MdArrowForward,
  MdCardMembership,
  MdInventory,
  MdPlaylistRemove,
  MdReadMore,
  MdCheckCircleOutline,
  MdContentPasteOff,
  MdOutlineConstruction,
  MdOutlineLayers,
  MdViewColumn,
  MdShelves,
  MdAssignmentInd,
};
